function [NEW_GRID,nnods] = gridCut(GRID,radius,hight_l,hight_r,lx)
%% gridCut.m
% Title: Grid modifier – notch removal at specimen sides
% Author: Przemysław Nosal
% ORCID: 0000-0001-9751-0071
% Affiliation: AGH University of Krakow
% Contact: pnosal@agh.edu.pl
% Date: 2025-04-22
% Version: 1.0
% Description: Removes nodes from a regular grid that fall within circular cutouts (notches) 
%              on the left and right edges of a rectangular specimen. Cutouts are defined 
%              by radius and notch center height on each side. The output grid is renumbered 
%              with continuous node IDs.
% Dependencies: Requires grid structure as generated by gridGenerator.m
% License: CC-BY 4.0

% -------------------------------------------------------------------------
% INPUTS:
% GRID     – initial grid matrix [nodeID, x, y, z, mass]
% radius   – radius of circular notches on the left and right
% hight_l  – vertical coordinate of left notch center
% hight_r  – vertical coordinate of right notch center
% lx       – total length of the plate (used to locate right notch)

% OUTPUTS:
% NEW_GRID – modified grid with removed nodes inside the notches and 
%            renumbered node IDs
% nnods    – total number of nodes after modification

% LOCAL VARIABLES:
% cut_l, cut_r – 2-element vectors storing the center coordinates of the left and right notch
% R1, R2       – distances from current node to each notch center
% count        – number of deleted nodes up to current iteration
% ii           – loop index
% -------------------------------------------------------------------------

cut_l = [0 hight_l];
cut_r = [lx hight_r];
count = 0;
for ii = 1:length(GRID)
    R1 = sqrt((GRID(ii,2)-cut_l(1,1))^2+(GRID(ii,3)-cut_l(1,2))^2);
    R2 = sqrt((GRID(ii,2)-cut_r(1,1))^2+(GRID(ii,3)-cut_r(1,2))^2);
    if R1 < radius
        count = count + 1;
    elseif R2 < radius
        count = count + 1;
    else
        % pass
        NEW_GRID(ii-count,:) = GRID(ii,:);
        NEW_GRID(ii-count,1) = NEW_GRID(ii-count,1) - count;
    end
end

nnods = length(NEW_GRID);