function [NEW_GRID,nnods] = gridCut_Hole(GRID, radius, x_center, y_center)
%% gridCut_Hole.m
% Title: Grid modifier – circular hole removal in specimen
% Author: Przemysław Nosal
% ORCID: 0000-0001-9751-0071
% Affiliation: AGH University of Krakow
% Contact: pnosal@agh.edu.pl
% Date: 2025-05-27
% Version: 1.0
% Description: Removes nodes from a regular grid that fall within a single 
%              circular hole located at a specified (x, y) coordinate.
%              The output grid is renumbered with continuous node IDs.
% Dependencies: Requires grid structure as generated by gridGenerator.m
% License: CC-BY 4.0

% -------------------------------------------------------------------------
% INPUTS:
% GRID      – initial grid matrix [nodeID, x, y, z, mass]
% radius    – radius of the circular hole
% x_center  – x coordinate of the hole center
% y_center  – y coordinate of the hole center

% OUTPUTS:
% NEW_GRID  – modified grid with removed nodes inside the hole and 
%             renumbered node IDs
% nnods     – total number of nodes after modification

% LOCAL VARIABLES:
% center    – 2-element vector with center coordinates of the hole
% R         – distance from current node to the hole center
% count     – number of deleted nodes up to current iteration
% ii        – loop index
% -------------------------------------------------------------------------

center = [x_center y_center];
count = 0;

for ii = 1:length(GRID)
    R = sqrt((GRID(ii,2)-center(1))^2 + (GRID(ii,3)-center(2))^2);
    if R < radius
        count = count + 1;
    else
        NEW_GRID(ii-count,:) = GRID(ii,:);
        NEW_GRID(ii-count,1) = NEW_GRID(ii-count,1) - count;
    end
end

nnods = length(NEW_GRID);
end